# Generated by Django 5.2.15 on 2026-06-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_category_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
