# Generated by Django 5.2.15 on 2026-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_knowledge_base_and_ai_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
