# Generated by Django 5.2.15 on 2026-06-30 11:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

TICKET_TRIGGER_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION app_ticket_search_vector_trigger() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.customer_name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.customer_email, '')), 'A') ||
        (
            SELECT coalesce(
                setweight(
                    to_tsvector('english', string_agg(body, ' ')),
                    'B'
                ),
                ''::tsvector
            )
            FROM app_message
            WHERE ticket_id = NEW.id
        );
    RETURN NEW;
END
$$ LANGUAGE plpgsql;
"""

TICKET_TRIGGER_SQL = """
CREATE TRIGGER ticket_search_vector_update
BEFORE INSERT OR UPDATE OF customer_name, customer_email
ON app_ticket
FOR EACH ROW EXECUTE FUNCTION app_ticket_search_vector_trigger();
"""

MESSAGE_TRIGGER_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION app_message_search_vector_trigger() RETURNS trigger AS $$
DECLARE
    affected_ticket_id bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        affected_ticket_id := OLD.ticket_id;
    ELSE
        affected_ticket_id := NEW.ticket_id;
    END IF;

    UPDATE app_ticket
    SET search_vector =
        setweight(to_tsvector('english', coalesce(customer_name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(customer_email, '')), 'A') ||
        (
            SELECT coalesce(
                setweight(
                    to_tsvector('english', string_agg(body, ' ')),
                    'B'
                ),
                ''::tsvector
            )
            FROM app_message
            WHERE ticket_id = affected_ticket_id
        )
    WHERE id = affected_ticket_id;

    RETURN NULL;
END
$$ LANGUAGE plpgsql;
"""

MESSAGE_TRIGGER_SQL = """
CREATE TRIGGER message_search_vector_update
AFTER INSERT OR UPDATE OF body OR DELETE
ON app_message
FOR EACH ROW EXECUTE FUNCTION app_message_search_vector_trigger();
"""

BACKFILL_SQL = """
UPDATE app_ticket SET customer_name = customer_name;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="ticket_search_vector_idx"
            ),
        ),
        migrations.RunSQL(
            sql=TICKET_TRIGGER_FUNCTION_SQL,
            reverse_sql="DROP FUNCTION IF EXISTS app_ticket_search_vector_trigger() CASCADE;",
        ),
        migrations.RunSQL(
            sql=TICKET_TRIGGER_SQL,
            reverse_sql="DROP TRIGGER IF EXISTS ticket_search_vector_update ON app_ticket;",
        ),
        migrations.RunSQL(
            sql=MESSAGE_TRIGGER_FUNCTION_SQL,
            reverse_sql="DROP FUNCTION IF EXISTS app_message_search_vector_trigger() CASCADE;",
        ),
        migrations.RunSQL(
            sql=MESSAGE_TRIGGER_SQL,
            reverse_sql="DROP TRIGGER IF EXISTS message_search_vector_update ON app_message;",
        ),
        migrations.RunSQL(
            sql=BACKFILL_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
