# Generated by Django 5.2.15 on 2026-07-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ticket_search_vector_ticket_ticket_search_vector_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google (Gemini)'), ('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('input_price_per_1k', models.DecimalField(decimal_places=6, max_digits=10)),
                ('output_price_per_1k', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google (Gemini)'), ('openai', 'OpenAI (ChatGPT)'), ('anthropic', 'Anthropic (Claude)')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('answer_generation', 'Answer generated after Gate 1 passed'), ('embedding', 'Embedding a Help Article chunk for search')], max_length=30)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='app.company')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='app.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'created_at'], name='app_aiusage_company_16fc2a_idx')],
            },
        ),
    ]
