# Generated by Django 5.2.15 on 2026-07-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aimodelpricing_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='app.message'),
        ),
    ]
